### ISSUE TITLE
Not working on certain websites

### ISSUE THREAD

**Issue by chaoscreater** [tophf/autopagerize#15]
I've tested Google and some other sites and this works great, but on some other sites it doesn't and it shows "no pageable content found". However, there are definitely pages on those sites that you can manually click into. Here's an example:

https://www.myrent.co.nz/listings

**Comment by tophf** [comment]
Rules are maintained in http://wedata.net/databases/autopagerize/items

**Comment by tophf** [comment]
You can add a custom rule yourself using DevTools + the existing rules as an example.

**Comment by chaoscreater** [comment]
All good, I just found another extension that works with that site:
https://chrome.google.com/webstore/detail/uautopagerize/kdplapeciagkkjoignnkfpbfkebcfbpb
