### ISSUE TITLE
Doesn't work with custom google searches.

### ISSUE THREAD

**Issue by ibay770** [tophf/autopagerize#16]
First, just wanted to thank you for your hard work in making a great extention!
Is it possible to get it working on sites with custom google searches? 
(https://www.searchcraigslist.net/results?q=car) as one example.

Thanks in advance.

**Comment by tophf** [comment]
It's a JS-based search that dynamically adds the new content. There are no actual links to the next page. I guess there may be other extensions that support this kind of setup.
