### ISSUE TITLE
A Request

### ISSUE THREAD

**Issue by Tanookirby** [tophf/autopagerize#2]
Hi,

I've heard that your version of autopagerize has a feature that allows images from google news and yahoo news to appear. I've been looking for a way to incorporate this into [my own modified version](https://addons.mozilla.org/en-US/firefox/addon/autopagerizeadvanced/). What lines of script should I put into the autopagerize.user.js file to make this work?

**Comment by tophf** [comment]
I can make a PR in your repo if you have one on github.

**Comment by Tanookirby** [comment]
I do. Get it [here](https://github.com/Tanookirby/Autopagerize-Advanced-for-Firefox).

**Comment by tophf** [comment]
Done.

**Comment by Tanookirby** [comment]
Well, I downloaded the extension from the repository, extracted the files, added your changes, and put the files into a new xpi file. But when I try to add it to my browser, I get a message saying it's corrupt.

**Comment by tophf** [comment]
I can't help with xpi stuff.
