### ISSUE TITLE
More Documentation for Custom Rules

### ISSUE THREAD

**Issue by anthonyattard** [tophf/autopagerize#3]
You should create some more accurate documentation on how to make custom rules. It's very unclear on how to set url, insertBefore, pageElement, and nextLink.

**Comment by tophf** [comment]
I agree it makes sense, but I thought it was documented many years ago somewhere for the original AutoPager addon. No promises I'll do it personally any time soon, though, because I think the syntax is pretty self-explanatory.

**Comment by tophf** [comment]
Meanwhile I've added an example underneath the rules sections:
![image](https://user-images.githubusercontent.com/1310400/64535455-00f54900-d320-11e9-80f2-9c84f87bd46b.png)

**Comment by anthonyattard** [comment]
Thank you! Much appreciated.

**Comment by machsix** [comment]
Hi, just for your information, I have maintained an enhanced userscript for the same purpose for a while. The project is located at https://github.com/machsix/Super-preloader.

I have also written document for the format of the rule. https://machsix.github.io/Super-preloader/en/siterule.html

The **The basic composition of the rules** should be compatible with your extension. You are also welcome to use my database of the rules https://machsix.github.io/Super-preloader/mydata.json, although most of them are for websites in Chinese.

**Comment by anthonyattard** [comment]
Thank you @machsix !
