### ISSUE TITLE
Problem with some sites

### ISSUE THREAD

**Issue by solara322** [tophf/autopagerize#4]
Does not work on Yandex, but the original extension that you forked works fine there (https://yandex.ua/search/?text=microsoft&lr=143)
Does not work on nozomi. And not one other extension or scripts that I found there does not work. (https://nozomi.la/) (NSFW)

**Comment by tophf** [comment]
Weirdly, Yandex doesn't work when I open the page, but it works if I reload it. I see similar behavior in google search. I'll try to fix it.

As for nozomi.la, it doesn't have a rule in the database.
