### ISSUE TITLE
How can I install it?

### ISSUE THREAD

**Issue by Rom888** [tophf/autopagerize#5]
Hi,
How can I install it?

**Comment by tophf** [comment]
Just like any other unpacked extension:
https://www.thesslstore.com/blog/install-a-chrome-extension-from-github/

**Comment by darkred** [comment]
I have already installed the unpacked extension and it's excellent! Thanks for your work, @tophf !

How about also uploading it to Chrome Web Store at some point
*(hoping that their review process will improve eventually, of course!*)

**Comment by tophf** [comment]
Their review process is a joke and an incredible pain in the ass. I don't think it'll ever change.
