### ISSUE TITLE
Please add some settings like Autopager add-on from Firefox

### ISSUE THREAD

**Issue by barbudo2005** [tophf/autopagerize#6]
Thank you for your fork. I am using it instead of the original Autopagerize extension.

I promove it in Vivaldi Browser Forum, so more people use it:

https://forum.vivaldi.net/topic/45544/a-better-autopagerize-extension

I use now your fork and Pagezipper because there are 6 sites that AP not control and Pagezipper does.

I would like to ask you to add some settings that Autopager from Firefox had, because there are sites that Pagezipper and AP don't control.

![image](https://user-images.githubusercontent.com/59028314/78946873-39b5f600-7a9a-11ea-89de-3d5dd747211d.png)

![image](https://user-images.githubusercontent.com/59028314/78946897-49353f00-7a9a-11ea-926c-3a93507e74f0.png)

The following settings in Autopager make the difference in some sites to me like:

1.- Enable Javascript while loading the page
2.- Force Javascript mode
3.- This is an ajax site
4.- Quick load
And others.

Would be possible?

For example this site:

https://www.epublibre.org/catalogo/index/0/publicado/novedades/sin/1

AP don't control and Pagezipper don't give the right next page.

The settings in Autopager are:

![image](https://user-images.githubusercontent.com/59028314/78949516-1ee77f80-7aa2-11ea-9017-126f0ff40150.png)

Thank you very much in advance

**Comment by tophf** [comment]
This is a fork of Autopagerize, a simplified variant of the original AP without its advanced settings or UI so I don't plan on adding them either.

Try switching to a more advanced variant: [Super-preloader](https://github.com/machsix/Super-preloader).
