### ISSUE TITLE
Autopagerize in Forums

### ISSUE THREAD

**Issue by barbudo2005** [tophf/autopagerize#8]
When I am looking a Forum with 2 pages and  arrive to the end of the second page, Autopagerize continue from the first page scrolling again.

Instead of finish the scrolling at the end of the second page.

![image](https://user-images.githubusercontent.com/59028314/83209563-0f45f800-a12f-11ea-9cac-e1aa058a380e.png)

![image](https://user-images.githubusercontent.com/59028314/83209602-21279b00-a12f-11ea-85d0-393f8e7f0540.png)

How could I fit this problem?

Thank you in advance.

**Comment by tophf** [comment]
It's a typical problem caused by some rule in the database used by the extension. You can exclude this forum's URL/domain in the popup.

![popup](https://camo.githubusercontent.com/f43f4a8193b977a72f27a230157b4f0b4a028a59/68747470733a2f2f692e696d6775722e636f6d2f615632637977382e706e67)
