### ISSUE TITLE
Chrome keeps removing this extension

### ISSUE THREAD

**Issue by Madddcow** [tophf/autopagerize#9]
Hi there.  This is a great fork but for some reason, Chrome keeps removing this extension.  It works for a while if I load it unpacked but after restarting my Mac, the extension has been removed.  If I try to pack the extension, Chrome simply disables it.

Is there any way to get this extension running correctly?  My version of Chrome is 83.0.4103.61 and I'm running it on macOS 10.15.5.

Cheers
Gary

**Comment by tophf** [comment]
I have no idea as I don't have a Mac. There's no special in this extension so it's a problem of Chrome in general for which there could be solutions, try searching. One thing I know: I won't publish this to the web store, most probably never, to me the entire store is a joke.

**Comment by Madddcow** [comment]
Thanks for replying.  I've already searched extensively for a solution but nothing works...it's weird.

________________________________

**Comment by tophf** [comment]
You can add `--load-extension=/path/to/ext` to your Chrome's command line, IIRC some tools/tricks exist for a Mac.

**Comment by TickleMyBells** [comment]
I had the same issue while using my macbook and somehow resolved it. Here is what I did:

▶︎ Remove the OG version from your extensions on chrome (if you have both unpacked) from chrome://extensions/ 
▶︎ After you downloaded the latest release zip and unzip it, keep it out of the Chrome folder/chrome extensions (i.e. make a personal "extensions for chrome" folder somewhere you can easily navigate to when you unpack it). Either your mac or chrome sees it as a potential threat and removes it (in my case, it had time machine load an earlier local snapshot).
▶︎ Try toggling the following in chrome://flags/
    • #extension-checkup
    • #extension-content-verification
    • #enable-experimental-web-platform-features
    • #debug-packed-apps
*only the last 2 flags are set to "enable" for me, the others are still set on "Default"

tophf rebuilt such a great extension that I highly encourage you to research around a bit by googling how to make your own extension and extrapolate the concept to fix w/e is happening on your end :) 

P.S: Thanks for all your hard work tophf! :)
